services:
  - type: web
    name: leafnote-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm run server
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CORS_ORIGIN
        value: https://ryu-s28.github.io
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: FIREBASE_COLLECTION
        value: leafnote
      - key: FIREBASE_DOC_ID
        value: main
